// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sga_stif.Models;

#nullable disable

namespace sga_stif.Migrations
{
    [DbContext(typeof(ContextoBaseDados))]
    [Migration("20220323172456_preenchimentoTabelaAgenciaInstituicaoFinanceira")]
    partial class preenchimentoTabelaAgenciaInstituicaoFinanceira
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("sga_stif.Models.Acao", b =>
                {
                    b.Property<int>("IdAcao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdAcao");

                    b.ToTable("Acao", (string)null);

                    b.HasData(
                        new
                        {
                            IdAcao = 1,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 55, 386, DateTimeKind.Local).AddTicks(1882),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 55, 386, DateTimeKind.Local).AddTicks(1863),
                            Eliminado = false,
                            Nome = "Criar"
                        },
                        new
                        {
                            IdAcao = 2,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 55, 386, DateTimeKind.Local).AddTicks(1892),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 55, 386, DateTimeKind.Local).AddTicks(1891),
                            Eliminado = false,
                            Nome = "Editar"
                        },
                        new
                        {
                            IdAcao = 3,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 55, 386, DateTimeKind.Local).AddTicks(1896),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 55, 386, DateTimeKind.Local).AddTicks(1895),
                            Eliminado = false,
                            Nome = "Eliminar"
                        });
                });

            modelBuilder.Entity("sga_stif.Models.Agencia", b =>
                {
                    b.Property<int>("IdAgencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdInstituicaoFinanceira")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdAgencia");

                    b.HasIndex("IdCidade");

                    b.HasIndex("IdInstituicaoFinanceira");

                    b.ToTable("Agencia", (string)null);

                    b.HasData(
                        new
                        {
                            IdAgencia = 1,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5606),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5605),
                            Eliminado = false,
                            IdCidade = 8,
                            IdInstituicaoFinanceira = 1,
                            Nome = "BCA"
                        });
                });

            modelBuilder.Entity("sga_stif.Models.Beneficiario", b =>
                {
                    b.Property<int>("IdBeneficiario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CinBi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSocio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroPassaporte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdBeneficiario");

                    b.HasIndex("IdSocio");

                    b.ToTable("Beneficiario", (string)null);
                });

            modelBuilder.Entity("sga_stif.Models.Cidade", b =>
                {
                    b.Property<int>("IdCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdIlha")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCidade");

                    b.HasIndex("IdIlha");

                    b.ToTable("Cidade", (string)null);

                    b.HasData(
                        new
                        {
                            IdCidade = 1,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5319),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5318),
                            Eliminado = false,
                            IdIlha = 8,
                            Nome = "Praia"
                        },
                        new
                        {
                            IdCidade = 2,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5328),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5326),
                            Eliminado = false,
                            IdIlha = 8,
                            Nome = "Outro"
                        },
                        new
                        {
                            IdCidade = 3,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5334),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5332),
                            Eliminado = false,
                            IdIlha = 2,
                            Nome = "Mindelo"
                        },
                        new
                        {
                            IdCidade = 4,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5339),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5337),
                            Eliminado = false,
                            IdIlha = 5,
                            Nome = "Santa Maria"
                        },
                        new
                        {
                            IdCidade = 5,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5343),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5342),
                            Eliminado = false,
                            IdIlha = 7,
                            Nome = "Vila do Maio"
                        },
                        new
                        {
                            IdCidade = 6,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5349),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5347),
                            Eliminado = false,
                            IdIlha = 8,
                            Nome = "Santa Cruz"
                        },
                        new
                        {
                            IdCidade = 7,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5354),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5352),
                            Eliminado = false,
                            IdIlha = 6,
                            Nome = "Sal Rei"
                        },
                        new
                        {
                            IdCidade = 8,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5358),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5357),
                            Eliminado = false,
                            IdIlha = 1,
                            Nome = "Porto Novo"
                        },
                        new
                        {
                            IdCidade = 9,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5363),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5361),
                            Eliminado = false,
                            IdIlha = 8,
                            Nome = "Ribeira Grande"
                        },
                        new
                        {
                            IdCidade = 10,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5367),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5366),
                            Eliminado = false,
                            IdIlha = 10,
                            Nome = "Ribeira Brava"
                        },
                        new
                        {
                            IdCidade = 11,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5372),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5370),
                            Eliminado = false,
                            IdIlha = 1,
                            Nome = "Tarrafal"
                        },
                        new
                        {
                            IdCidade = 12,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5376),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5375),
                            Eliminado = false,
                            IdIlha = 5,
                            Nome = "Espargos"
                        },
                        new
                        {
                            IdCidade = 13,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5381),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5379),
                            Eliminado = false,
                            IdIlha = 8,
                            Nome = "Assomada"
                        },
                        new
                        {
                            IdCidade = 14,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5385),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5384),
                            Eliminado = false,
                            IdIlha = 8,
                            Nome = "São Domingos"
                        },
                        new
                        {
                            IdCidade = 15,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5390),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5388),
                            Eliminado = false,
                            IdIlha = 9,
                            Nome = "São Filipe"
                        },
                        new
                        {
                            IdCidade = 16,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5394),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5392),
                            Eliminado = false,
                            IdIlha = 9,
                            Nome = "Mosteiros"
                        },
                        new
                        {
                            IdCidade = 17,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5399),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5397),
                            Eliminado = false,
                            IdIlha = 1,
                            Nome = "Nova Sintra"
                        },
                        new
                        {
                            IdCidade = 18,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5403),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5402),
                            Eliminado = false,
                            IdIlha = 8,
                            Nome = "Tarrafal (Santiano)"
                        });
                });

            modelBuilder.Entity("sga_stif.Models.EstadoSocio", b =>
                {
                    b.Property<int>("IdEstadoSocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSocio")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdEstadoSocio");

                    b.HasIndex("IdSocio");

                    b.ToTable("EstadoSocio", (string)null);
                });

            modelBuilder.Entity("sga_stif.Models.Ilha", b =>
                {
                    b.Property<int>("IdIlha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdIlha");

                    b.ToTable("Ilha", (string)null);

                    b.HasData(
                        new
                        {
                            IdIlha = 1,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5130),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5128),
                            Eliminado = false,
                            Nome = "Santo Antão"
                        },
                        new
                        {
                            IdIlha = 2,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5210),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5209),
                            Eliminado = false,
                            Nome = "São Vicente"
                        },
                        new
                        {
                            IdIlha = 3,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5217),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5215),
                            Eliminado = false,
                            Nome = "Santa Luzia"
                        },
                        new
                        {
                            IdIlha = 4,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5222),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5220),
                            Eliminado = false,
                            Nome = "São Nicolau"
                        },
                        new
                        {
                            IdIlha = 5,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5226),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5225),
                            Eliminado = false,
                            Nome = "Sal"
                        },
                        new
                        {
                            IdIlha = 6,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5231),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5229),
                            Eliminado = false,
                            Nome = "Boavista"
                        },
                        new
                        {
                            IdIlha = 7,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5236),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5234),
                            Eliminado = false,
                            Nome = "Maio"
                        },
                        new
                        {
                            IdIlha = 8,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5240),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5239),
                            Eliminado = false,
                            Nome = "Santiago"
                        },
                        new
                        {
                            IdIlha = 9,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5245),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5243),
                            Eliminado = false,
                            Nome = "Fogo"
                        },
                        new
                        {
                            IdIlha = 10,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5250),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5248),
                            Eliminado = false,
                            Nome = "Brava"
                        });
                });

            modelBuilder.Entity("sga_stif.Models.InstituicaoFinanceira", b =>
                {
                    b.Property<int>("IdInstituicaoFinanceira")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdInstituicaoFinanceira");

                    b.ToTable("InstituicaoFinanceira", (string)null);

                    b.HasData(
                        new
                        {
                            IdInstituicaoFinanceira = 1,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5557),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5556),
                            Eliminado = false,
                            Nome = "BCA"
                        });
                });

            modelBuilder.Entity("sga_stif.Models.Joia", b =>
                {
                    b.Property<int>("IdJoia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montante")
                        .HasColumnType("TEXT");

                    b.HasKey("IdJoia");

                    b.ToTable("Joia", (string)null);
                });

            modelBuilder.Entity("sga_stif.Models.JoiaSocio", b =>
                {
                    b.Property<int>("IdJoiaSocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdJoia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSocio")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montante")
                        .HasColumnType("TEXT");

                    b.HasKey("IdJoiaSocio");

                    b.HasIndex("IdJoia");

                    b.HasIndex("IdSocio");

                    b.ToTable("JoiaSocio", (string)null);
                });

            modelBuilder.Entity("sga_stif.Models.Menu", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdMenuPai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdMenu");

                    b.ToTable("Menu", (string)null);

                    b.HasData(
                        new
                        {
                            IdMenu = 1,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 55, 386, DateTimeKind.Local).AddTicks(2073),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 55, 386, DateTimeKind.Local).AddTicks(2072),
                            Descricao = "Administração do Sistema SGA-STIF",
                            Eliminado = false,
                            Nome = "Administração"
                        },
                        new
                        {
                            IdMenu = 2,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 55, 386, DateTimeKind.Local).AddTicks(2081),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 55, 386, DateTimeKind.Local).AddTicks(2080),
                            Descricao = "Gestão dos utilizadores",
                            Eliminado = false,
                            IdMenuPai = 1,
                            Nome = "Utilizador"
                        },
                        new
                        {
                            IdMenu = 3,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 55, 386, DateTimeKind.Local).AddTicks(2088),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 55, 386, DateTimeKind.Local).AddTicks(2087),
                            Descricao = "Gestão dos utilizadores",
                            Eliminado = false,
                            IdMenuPai = 1,
                            Nome = "Perfil"
                        },
                        new
                        {
                            IdMenu = 4,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 55, 386, DateTimeKind.Local).AddTicks(2091),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 55, 386, DateTimeKind.Local).AddTicks(2090),
                            Descricao = "Gestão dos utilizadores",
                            Eliminado = false,
                            IdMenuPai = 1,
                            Nome = "Menu"
                        });
                });

            modelBuilder.Entity("sga_stif.Models.MenuAcao", b =>
                {
                    b.Property<int>("IdMenuAcao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdAcao")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdMenu")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdMenuAcao");

                    b.HasIndex("IdAcao");

                    b.HasIndex("IdMenu");

                    b.ToTable("MenuAcao", (string)null);
                });

            modelBuilder.Entity("sga_stif.Models.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPerfil");

                    b.ToTable("Perfil", (string)null);

                    b.HasData(
                        new
                        {
                            IdPerfil = 1,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5498),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5496),
                            Descricao = "Administrador",
                            Eliminado = false
                        },
                        new
                        {
                            IdPerfil = 2,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5506),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5505),
                            Descricao = "Operador",
                            Eliminado = false
                        });
                });

            modelBuilder.Entity("sga_stif.Models.PerfilMenuAcao", b =>
                {
                    b.Property<int>("IdPerfilMenuAcao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMenuAcao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPPerfil")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPerfilMenuAcao");

                    b.HasIndex("IdMenuAcao");

                    b.HasIndex("IdPPerfil");

                    b.ToTable("PerfilMenuAcao", (string)null);
                });

            modelBuilder.Entity("sga_stif.Models.PeriodoQuota", b =>
                {
                    b.Property<int>("IdPeriodoQuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPeriodoQuota");

                    b.ToTable("PeriodoQuota", (string)null);
                });

            modelBuilder.Entity("sga_stif.Models.QuotaSocio", b =>
                {
                    b.Property<int>("IdQuotaSocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPeriodoQuota")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSocio")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montante")
                        .HasColumnType("TEXT");

                    b.HasKey("IdQuotaSocio");

                    b.HasIndex("IdPeriodoQuota");

                    b.HasIndex("IdSocio");

                    b.ToTable("QuotaSocio");
                });

            modelBuilder.Entity("sga_stif.Models.Socio", b =>
                {
                    b.Property<int>("IdSocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CinBi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("BLOB");

                    b.Property<int>("IdAgencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipoQuota")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipologiaSocio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroPassaporte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdSocio");

                    b.HasIndex("IdAgencia");

                    b.HasIndex("IdTipoQuota");

                    b.HasIndex("IdTipologiaSocio");

                    b.ToTable("Socio", (string)null);
                });

            modelBuilder.Entity("sga_stif.Models.TipologiaSocio", b =>
                {
                    b.Property<int>("IdTipologiaSocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montante")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridicidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTipologiaSocio");

                    b.ToTable("TipologiaSocio", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipologiaSocio = 1,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(4597),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(4573),
                            DataFim = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(4614),
                            DataInicio = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(4617),
                            Descricao = "Normal",
                            Eliminado = false,
                            Montante = 0m,
                            Prioridicidade = 1,
                            Tipo = 0
                        },
                        new
                        {
                            IdTipologiaSocio = 2,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(4623),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(4621),
                            DataFim = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(4627),
                            DataInicio = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(4629),
                            Descricao = "Honorário",
                            Eliminado = false,
                            Montante = 0m,
                            Prioridicidade = 1,
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("sga_stif.Models.TipoQuota", b =>
                {
                    b.Property<int>("IdTipoQuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montante")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priodicidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTipoQuota");

                    b.ToTable("TipoQuota", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoQuota = 1,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5003),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5000),
                            Descricao = "Quinzenal",
                            Eliminado = false,
                            Montante = 0m,
                            Priodicidade = 1,
                            Tipo = 0
                        },
                        new
                        {
                            IdTipoQuota = 2,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5020),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5013),
                            Descricao = "Mensal",
                            Eliminado = false,
                            Montante = 0m,
                            Priodicidade = 1,
                            Tipo = 0
                        },
                        new
                        {
                            IdTipoQuota = 3,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5047),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5045),
                            Descricao = "Trimestral",
                            Eliminado = false,
                            Montante = 0m,
                            Priodicidade = 1,
                            Tipo = 0
                        },
                        new
                        {
                            IdTipoQuota = 4,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5052),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5050),
                            Descricao = "Semestral",
                            Eliminado = false,
                            Montante = 0m,
                            Priodicidade = 1,
                            Tipo = 0
                        },
                        new
                        {
                            IdTipoQuota = 5,
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5064),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5062),
                            Descricao = "Anual",
                            Eliminado = false,
                            Montante = 0m,
                            Priodicidade = 1,
                            Tipo = 0
                        });
                });

            modelBuilder.Entity("sga_stif.Models.Utilizador", b =>
                {
                    b.Property<int>("IdUtilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("BLOB");

                    b.Property<int?>("IdPerfil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeUtilizador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PalavraPasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUtilizador");

                    b.HasIndex("IdPerfil");

                    b.ToTable("Utilizador", (string)null);

                    b.HasData(
                        new
                        {
                            IdUtilizador = 1,
                            Apelido = "Semedo",
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5666),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 376, DateTimeKind.Local).AddTicks(5665),
                            Eliminado = false,
                            Email = "angelosemedo@sgastif.cv",
                            IdPerfil = 1,
                            Nome = "Angelo",
                            NomeUtilizador = "angelosemedo",
                            PalavraPasse = "$2a$11$9W5lkLBaPWN2z2gD1qJ82.n4CJPdBxMNTzZzCZ94bwbXXWvGfaAbe"
                        },
                        new
                        {
                            IdUtilizador = 2,
                            Apelido = "Veiga",
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 54, 713, DateTimeKind.Local).AddTicks(3818),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 54, 713, DateTimeKind.Local).AddTicks(3797),
                            Eliminado = false,
                            Email = "odailtonveiga@sgastif.cv",
                            IdPerfil = 1,
                            Nome = "Odailton",
                            NomeUtilizador = "odailtonveiga",
                            PalavraPasse = "$2a$11$fS5gjCs1U8GiTcqwFZf5BOVWhx6YUXhxH/72aGnqmgD.ZLdmhucza"
                        },
                        new
                        {
                            IdUtilizador = 3,
                            Apelido = "Varela",
                            DataAtualizacao = new DateTime(2022, 3, 23, 16, 24, 55, 52, DateTimeKind.Local).AddTicks(9435),
                            DataCriacao = new DateTime(2022, 3, 23, 16, 24, 55, 52, DateTimeKind.Local).AddTicks(9413),
                            Eliminado = false,
                            Email = "manuelvarela@sgastif.cv",
                            IdPerfil = 1,
                            Nome = "Manuel",
                            NomeUtilizador = "manuelvarela",
                            PalavraPasse = "$2a$11$JyiiN99kf0ZLr48NyUf.SO.LW2Gb3p/RvXP0VX6pTgvoWUbxtbMbW"
                        });
                });

            modelBuilder.Entity("sga_stif.Models.Agencia", b =>
                {
                    b.HasOne("sga_stif.Models.Cidade", "Cidade")
                        .WithMany("Agencia")
                        .HasForeignKey("IdCidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sga_stif.Models.InstituicaoFinanceira", "InstituicaoFinanceira")
                        .WithMany("Agencia")
                        .HasForeignKey("IdInstituicaoFinanceira")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("InstituicaoFinanceira");
                });

            modelBuilder.Entity("sga_stif.Models.Beneficiario", b =>
                {
                    b.HasOne("sga_stif.Models.Socio", "Socio")
                        .WithMany("Beneficiario")
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("sga_stif.Models.Cidade", b =>
                {
                    b.HasOne("sga_stif.Models.Ilha", "Ilha")
                        .WithMany("Cidade")
                        .HasForeignKey("IdIlha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilha");
                });

            modelBuilder.Entity("sga_stif.Models.EstadoSocio", b =>
                {
                    b.HasOne("sga_stif.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("sga_stif.Models.JoiaSocio", b =>
                {
                    b.HasOne("sga_stif.Models.Joia", "Joia")
                        .WithMany("JoiaSocio")
                        .HasForeignKey("IdJoia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sga_stif.Models.Socio", "Socio")
                        .WithMany("JoiaSocio")
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joia");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("sga_stif.Models.MenuAcao", b =>
                {
                    b.HasOne("sga_stif.Models.Acao", "Acao")
                        .WithMany("MenuAcao")
                        .HasForeignKey("IdAcao");

                    b.HasOne("sga_stif.Models.Menu", "Menu")
                        .WithMany("MenuAcao")
                        .HasForeignKey("IdMenu");

                    b.Navigation("Acao");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("sga_stif.Models.PerfilMenuAcao", b =>
                {
                    b.HasOne("sga_stif.Models.MenuAcao", "MenuAcao")
                        .WithMany("PerfilMenuAcao")
                        .HasForeignKey("IdMenuAcao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sga_stif.Models.Perfil", "Perfil")
                        .WithMany("PerfilMenuAcao")
                        .HasForeignKey("IdPPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuAcao");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("sga_stif.Models.QuotaSocio", b =>
                {
                    b.HasOne("sga_stif.Models.PeriodoQuota", "PeriodoQuota")
                        .WithMany("QuotaSocio")
                        .HasForeignKey("IdPeriodoQuota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sga_stif.Models.Socio", "Socio")
                        .WithMany("QuotaSocio")
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodoQuota");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("sga_stif.Models.Socio", b =>
                {
                    b.HasOne("sga_stif.Models.Agencia", "Agencia")
                        .WithMany("Socio")
                        .HasForeignKey("IdAgencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sga_stif.Models.TipoQuota", "TipoQuota")
                        .WithMany("Socio")
                        .HasForeignKey("IdTipoQuota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sga_stif.Models.TipologiaSocio", "TipologiaSocio")
                        .WithMany("Socio")
                        .HasForeignKey("IdTipologiaSocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("TipoQuota");

                    b.Navigation("TipologiaSocio");
                });

            modelBuilder.Entity("sga_stif.Models.Utilizador", b =>
                {
                    b.HasOne("sga_stif.Models.Perfil", "Perfil")
                        .WithMany("Utilizador")
                        .HasForeignKey("IdPerfil");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("sga_stif.Models.Acao", b =>
                {
                    b.Navigation("MenuAcao");
                });

            modelBuilder.Entity("sga_stif.Models.Agencia", b =>
                {
                    b.Navigation("Socio");
                });

            modelBuilder.Entity("sga_stif.Models.Cidade", b =>
                {
                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("sga_stif.Models.Ilha", b =>
                {
                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("sga_stif.Models.InstituicaoFinanceira", b =>
                {
                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("sga_stif.Models.Joia", b =>
                {
                    b.Navigation("JoiaSocio");
                });

            modelBuilder.Entity("sga_stif.Models.Menu", b =>
                {
                    b.Navigation("MenuAcao");
                });

            modelBuilder.Entity("sga_stif.Models.MenuAcao", b =>
                {
                    b.Navigation("PerfilMenuAcao");
                });

            modelBuilder.Entity("sga_stif.Models.Perfil", b =>
                {
                    b.Navigation("PerfilMenuAcao");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("sga_stif.Models.PeriodoQuota", b =>
                {
                    b.Navigation("QuotaSocio");
                });

            modelBuilder.Entity("sga_stif.Models.Socio", b =>
                {
                    b.Navigation("Beneficiario");

                    b.Navigation("JoiaSocio");

                    b.Navigation("QuotaSocio");
                });

            modelBuilder.Entity("sga_stif.Models.TipologiaSocio", b =>
                {
                    b.Navigation("Socio");
                });

            modelBuilder.Entity("sga_stif.Models.TipoQuota", b =>
                {
                    b.Navigation("Socio");
                });
#pragma warning restore 612, 618
        }
    }
}
