// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sga_stif.Models;

#nullable disable

namespace sga_stif.Migrations
{
    [DbContext(typeof(ContextoBaseDados))]
    partial class ContextoBaseDadosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("sga_stif.Models.Acao", b =>
                {
                    b.Property<int>("IdAcao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdAcao");

                    b.ToTable("Acao", (string)null);

                    b.HasData(
                        new
                        {
                            IdAcao = 1,
                            DataAtualizacao = new DateTime(2022, 3, 19, 22, 16, 34, 781, DateTimeKind.Local).AddTicks(9020),
                            DataCriacao = new DateTime(2022, 3, 19, 22, 16, 34, 781, DateTimeKind.Local).AddTicks(8990),
                            Eliminado = false,
                            Nome = "Criar"
                        },
                        new
                        {
                            IdAcao = 2,
                            DataAtualizacao = new DateTime(2022, 3, 19, 22, 16, 34, 781, DateTimeKind.Local).AddTicks(9040),
                            DataCriacao = new DateTime(2022, 3, 19, 22, 16, 34, 781, DateTimeKind.Local).AddTicks(9030),
                            Eliminado = false,
                            Nome = "Editar"
                        },
                        new
                        {
                            IdAcao = 3,
                            DataAtualizacao = new DateTime(2022, 3, 19, 22, 16, 34, 781, DateTimeKind.Local).AddTicks(9070),
                            DataCriacao = new DateTime(2022, 3, 19, 22, 16, 34, 781, DateTimeKind.Local).AddTicks(9070),
                            Eliminado = false,
                            Nome = "Eliminar"
                        });
                });

            modelBuilder.Entity("sga_stif.Models.Menu", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdMenuPai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdMenu");

                    b.ToTable("Menu", (string)null);

                    b.HasData(
                        new
                        {
                            IdMenu = 1,
                            DataAtualizacao = new DateTime(2022, 3, 19, 22, 16, 34, 781, DateTimeKind.Local).AddTicks(9100),
                            DataCriacao = new DateTime(2022, 3, 19, 22, 16, 34, 781, DateTimeKind.Local).AddTicks(9100),
                            Descricao = "Administração do Sistema SGA-STIF",
                            Eliminado = false,
                            Nome = "Administração"
                        },
                        new
                        {
                            IdMenu = 2,
                            DataAtualizacao = new DateTime(2022, 3, 19, 22, 16, 34, 781, DateTimeKind.Local).AddTicks(9110),
                            DataCriacao = new DateTime(2022, 3, 19, 22, 16, 34, 781, DateTimeKind.Local).AddTicks(9110),
                            Descricao = "Gestão dos utilizadores",
                            Eliminado = false,
                            IdMenuPai = 1,
                            Nome = "Utilizador"
                        },
                        new
                        {
                            IdMenu = 3,
                            DataAtualizacao = new DateTime(2022, 3, 19, 22, 16, 34, 781, DateTimeKind.Local).AddTicks(9110),
                            DataCriacao = new DateTime(2022, 3, 19, 22, 16, 34, 781, DateTimeKind.Local).AddTicks(9110),
                            Descricao = "Gestão dos utilizadores",
                            Eliminado = false,
                            IdMenuPai = 1,
                            Nome = "Perfil"
                        },
                        new
                        {
                            IdMenu = 4,
                            DataAtualizacao = new DateTime(2022, 3, 19, 22, 16, 34, 781, DateTimeKind.Local).AddTicks(9120),
                            DataCriacao = new DateTime(2022, 3, 19, 22, 16, 34, 781, DateTimeKind.Local).AddTicks(9120),
                            Descricao = "Gestão dos utilizadores",
                            Eliminado = false,
                            IdMenuPai = 1,
                            Nome = "Menu"
                        });
                });

            modelBuilder.Entity("sga_stif.Models.MenuAcao", b =>
                {
                    b.Property<int>("IdMenuAcao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdAcao")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdMenu")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdMenuAcao");

                    b.HasIndex("IdAcao");

                    b.HasIndex("IdMenu");

                    b.ToTable("MenuAcao", (string)null);
                });

            modelBuilder.Entity("sga_stif.Models.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPerfil");

                    b.ToTable("Perfil", (string)null);

                    b.HasData(
                        new
                        {
                            IdPerfil = 1,
                            DataAtualizacao = new DateTime(2022, 3, 19, 22, 16, 34, 240, DateTimeKind.Local).AddTicks(7030),
                            DataCriacao = new DateTime(2022, 3, 19, 22, 16, 34, 240, DateTimeKind.Local).AddTicks(7000),
                            Descricao = "Administrador",
                            Eliminado = false
                        },
                        new
                        {
                            IdPerfil = 2,
                            DataAtualizacao = new DateTime(2022, 3, 19, 22, 16, 34, 240, DateTimeKind.Local).AddTicks(7050),
                            DataCriacao = new DateTime(2022, 3, 19, 22, 16, 34, 240, DateTimeKind.Local).AddTicks(7050),
                            Descricao = "Operador",
                            Eliminado = false
                        });
                });

            modelBuilder.Entity("sga_stif.Models.Utilizador", b =>
                {
                    b.Property<int>("IdUtilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("BLOB");

                    b.Property<int?>("IdPerfil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeUtilizador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PalavraPasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUtilizador");

                    b.HasIndex("IdPerfil");

                    b.ToTable("Utilizador", (string)null);

                    b.HasData(
                        new
                        {
                            IdUtilizador = 1,
                            Apelido = "Semedo",
                            DataAtualizacao = new DateTime(2022, 3, 19, 22, 16, 34, 240, DateTimeKind.Local).AddTicks(7210),
                            DataCriacao = new DateTime(2022, 3, 19, 22, 16, 34, 240, DateTimeKind.Local).AddTicks(7200),
                            Eliminado = false,
                            Email = "angelosemedo@sgastif.cv",
                            IdPerfil = 1,
                            Nome = "Angelo",
                            NomeUtilizador = "angelosemedo",
                            PalavraPasse = "$2a$11$6cbodHrGQfY8GXu53Kd7g.voZ49pqI66K36py7TI1HWOMLl2qc4C."
                        },
                        new
                        {
                            IdUtilizador = 2,
                            Apelido = "Veiga",
                            DataAtualizacao = new DateTime(2022, 3, 19, 22, 16, 34, 420, DateTimeKind.Local).AddTicks(1320),
                            DataCriacao = new DateTime(2022, 3, 19, 22, 16, 34, 420, DateTimeKind.Local).AddTicks(1290),
                            Eliminado = false,
                            Email = "odailtonveiga@sgastif.cv",
                            IdPerfil = 1,
                            Nome = "Odailton",
                            NomeUtilizador = "odailtonveiga",
                            PalavraPasse = "$2a$11$fX0yhLZ17JTouIHm9IpO4utW/wrOTziEREkY4uwq.wqbau0CKJz2K"
                        },
                        new
                        {
                            IdUtilizador = 3,
                            Apelido = "Varela",
                            DataAtualizacao = new DateTime(2022, 3, 19, 22, 16, 34, 600, DateTimeKind.Local).AddTicks(1890),
                            DataCriacao = new DateTime(2022, 3, 19, 22, 16, 34, 600, DateTimeKind.Local).AddTicks(1850),
                            Eliminado = false,
                            Email = "manuelvarela@sgastif.cv",
                            IdPerfil = 1,
                            Nome = "Manuel",
                            NomeUtilizador = "manuelvarela",
                            PalavraPasse = "$2a$11$QLngQxQNs3rpsuivgaXx6e/ueMOLWlnaHEltlzBYBYB3u92GINj8G"
                        });
                });

            modelBuilder.Entity("sga_stif.Models.MenuAcao", b =>
                {
                    b.HasOne("sga_stif.Models.Acao", "Acao")
                        .WithMany("MenuAcao")
                        .HasForeignKey("IdAcao");

                    b.HasOne("sga_stif.Models.Menu", "Menu")
                        .WithMany("MenuAcao")
                        .HasForeignKey("IdMenu");

                    b.Navigation("Acao");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("sga_stif.Models.Utilizador", b =>
                {
                    b.HasOne("sga_stif.Models.Perfil", "Perfil")
                        .WithMany("Utilizador")
                        .HasForeignKey("IdPerfil");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("sga_stif.Models.Acao", b =>
                {
                    b.Navigation("MenuAcao");
                });

            modelBuilder.Entity("sga_stif.Models.Menu", b =>
                {
                    b.Navigation("MenuAcao");
                });

            modelBuilder.Entity("sga_stif.Models.Perfil", b =>
                {
                    b.Navigation("Utilizador");
                });
#pragma warning restore 612, 618
        }
    }
}
